const MAIN_TITLE = "Page Title";
const PAGE_CONTENT = [
    {
        'header': 'First section',
        'text': ['1 Lorem ipsum dolor sit amet consectetur adipiscing elit neque per sollicitudin taciti, viverra eros turpis rutrum magnis potenti tortor torquent dis posuere, tempus nam sodales fusce bibendum inceptos augue praesent feugiat vulputate. Molestie hendrerit cum placerat varius volutpat sem pellentesque vel nam ridiculus, sociis habitant fusce gravida nunc class faucibus dictumst eleifend, a commodo curae nostra tellus augue quisque rhoncus orci. Condimentum taciti metus himenaeos proin platea pulvinar litora cum nec, risus ridiculus imperdiet dis magna scelerisque sapien hac primis tempus, malesuada dignissim sollicitudin neque lectus nisl libero ante. Viverra mus ultricies blandit pretium eleifend eros sem aliquet, commodo ad platea per turpis ullamcorper. Tristique vulputate vel pretium odio aliquam fermentum interdum, proin dictumst habitasse fusce dis vehicula, pharetra inceptos nisi at cursus placerat. Phasellus dictumst blandit felis molestie vivamus tristique, class cras dui commodo nulla vehicula nibh, ultricies congue augue tempus bibendum. Nulla nibh et tincidunt taciti penatibus himenaeos convallis magnis, neque dapibus hendrerit justo diam etiam nullam, feugiat dui eleifend porta potenti rhoncus nisl.'],
        'background':'',
        'font':''
    },
    {
        'header': 'Second section',
        'text': [
            '2 Lorem ipsum dolor sit amet consectetur adipiscing elit neque per sollicitudin taciti, viverra eros turpis rutrum magnis potenti tortor torquent dis posuere, tempus nam sodales fusce bibendum inceptos augue praesent feugiat vulputate. Molestie hendrerit cum placerat varius volutpat sem pellentesque vel nam ridiculus, sociis habitant fusce gravida nunc class faucibus dictumst eleifend, a commodo curae nostra tellus augue quisque rhoncus orci. Condimentum taciti metus himenaeos proin platea pulvinar litora cum nec, risus ridiculus imperdiet dis magna scelerisque sapien hac primis tempus, malesuada dignissim sollicitudin neque lectus nisl libero ante. Viverra mus ultricies blandit pretium eleifend eros sem aliquet, commodo ad platea per turpis ullamcorper. Tristique vulputate vel pretium odio aliquam fermentum interdum, proin dictumst habitasse fusce dis vehicula, pharetra inceptos nisi at cursus placerat. Phasellus dictumst blandit felis molestie vivamus tristique, class cras dui commodo nulla vehicula nibh, ultricies congue augue tempus bibendum. Nulla nibh et tincidunt taciti penatibus himenaeos convallis magnis, neque dapibus hendrerit justo diam etiam nullam, feugiat dui eleifend porta potenti rhoncus nisl.',
            'Lorem ipsum dolor sit amet consectetur adipiscing elit neque per sollicitudin taciti, viverra eros turpis rutrum magnis potenti tortor torquent dis posuere, tempus nam sodales fusce bibendum inceptos augue praesent feugiat vulputate. Molestie hendrerit cum placerat varius volutpat sem pellentesque vel nam ridiculus, sociis habitant fusce gravida nunc class faucibus dictumst eleifend, a commodo curae nostra tellus augue quisque rhoncus orci. Condimentum taciti metus himenaeos proin platea pulvinar litora cum nec, risus ridiculus imperdiet dis magna scelerisque sapien hac primis tempus, malesuada dignissim sollicitudin neque lectus nisl libero ante. Viverra mus ultricies blandit pretium eleifend eros sem aliquet, commodo ad platea per turpis ullamcorper. Tristique vulputate vel pretium odio aliquam fermentum interdum, proin dictumst habitasse fusce dis vehicula, pharetra inceptos nisi at cursus placerat. Phasellus dictumst blandit felis molestie vivamus tristique, class cras dui commodo nulla vehicula nibh, ultricies congue augue tempus bibendum. Nulla nibh et tincidunt taciti penatibus himenaeos convallis magnis, neque dapibus hendrerit justo diam etiam nullam, feugiat dui eleifend porta potenti rhoncus nisl.'
        ],
        'background':'',
        'font':'white'},
    {
        'header': 'Third section',
        'text': ['3 Lorem ipsum dolor sit amet consectetur adipiscing elit neque per sollicitudin taciti, viverra eros turpis rutrum magnis potenti tortor torquent dis posuere, tempus nam sodales fusce bibendum inceptos augue praesent feugiat vulputate. Molestie hendrerit cum placerat varius volutpat sem pellentesque vel nam ridiculus, sociis habitant fusce gravida nunc class faucibus dictumst eleifend, a commodo curae nostra tellus augue quisque rhoncus orci. Condimentum taciti metus himenaeos proin platea pulvinar litora cum nec, risus ridiculus imperdiet dis magna scelerisque sapien hac primis tempus, malesuada dignissim sollicitudin neque lectus nisl libero ante. Viverra mus ultricies blandit pretium eleifend eros sem aliquet, commodo ad platea per turpis ullamcorper. Tristique vulputate vel pretium odio aliquam fermentum interdum, proin dictumst habitasse fusce dis vehicula, pharetra inceptos nisi at cursus placerat. Phasellus dictumst blandit felis molestie vivamus tristique, class cras dui commodo nulla vehicula nibh, ultricies congue augue tempus bibendum. Nulla nibh et tincidunt taciti penatibus himenaeos convallis magnis, neque dapibus hendrerit justo diam etiam nullam, feugiat dui eleifend porta potenti rhoncus nisl.'],
        'background':'',
        'font':''}
];